### ISSUE TITLE
Build fails on 4.07.1+musl+static+flambda and other cases without dynamic linking

### ISSUE THREAD

**Issue by hcarty** [dbuenzli/cmdliner#107]
From `Makefile` it looks like cmdliner assumes that the presence of `ocamlopt` means dynamic linking is available.  This isn't the case, however, for a switch like `4.07.1+musl+static+flambda` which does have a working `ocamlopt` but does not support dynamic linking.

**Comment by dbuenzli** [comment]
`ocamlc -config` still doesn't have the variable and the discovery logic [is ugly](https://github.com/dbuenzli/topkg/blob/64faa5913ea2fdf4cd8d5e57e35b788001e853bb/src/topkg_conf.ml#L562-L564).

It seems the way to go is to include `$(ocamlc -where)/Makefile.config` as suggested [here](https://github.com/dbuenzli/cmdliner/issues/104#issuecomment-456768662). Since 4.03 there [should be](https://github.com/ocaml/ocaml/issues/7172#issuecomment-473056934) a NATDYNLINK variable. Also this would allow to directly solve https://github.com/dbuenzli/cmdliner/issues/104.

Not sure I'll have the time immediately tough. A work around is to overlay an `opam` file that invokes `dune` build system.

**Comment by dbuenzli** [comment]
Actually the whole machinery was already in place so it was an easy fix could you please confirm the fix works by pinning current master.

**Comment by hcarty** [comment]
Seems to be ok - sorry for taking so long to respond!
