### ISSUE TITLE
opt_all + env variable ?

### ISSUE THREAD

**Issue by giltho** [dbuenzli/cmdliner#117]
Hi !
Here's my use case : I'm trying to write something that pretty much looks like a compiler. It may need to know the path of the runtime.

I want the path of the runtime either :
- to be passed through :  `-R/path/to/runtime/ -R/path/to/rest/of/runtime``
- or to be passe through a global variable `RUNTIME_PATH` which would contain a single string of path separated by `:`  in the style of the `PATH` env var.

So far i've written this 
```
let runtime_path =
     let doc = "Specify runtime library path for imports." in
     let docv = "RUNTIME_PATH" in
     Arg.(value &  opt_all string [] & info ["R"; "runtime"] ~doc ~docv)
```

But if I try to add an ~env variable, then I would get a single string. I would basically need a different converter for said env var. Is it possible ? Otherwise I'll just retrieve the env var if the list is empty, not so much of a blocker, it would just be the tiniest bit more elegant to do that directly through cmdliner.

If not possible, do you think that could be an interesting feature to add ?

PS: This library is just fantastic, thank you for your work

**Comment by dbuenzli** [comment]
> If not possible, do you think that could be an interesting feature to add ?

You could try to come up with a proposal but I suspect it will complexify the API for little returns. There's also more than one way you might want to do this -- for example you could say that CLI flags *extend* on the left or on the right your runtime path rather than replace it. If you can come up with an API and show that change is not too invasive I *may* consider. But I doubt.

Your solution seems fine (you can also hide your lookup in the `runtime_path` term itself).
