### ISSUE TITLE
Pager help pages broken when setting PAGER=less 

### ISSUE THREAD

**Issue by nojb** [dbuenzli/cmdliner#167]
This is a report that came from the Dune team. Recently Dune upgraded its vendored copy of `cmdliner` to 1.1.1, and users who set `PAGER=less` (a usual setting) find that their help pages are broken (because color codes are not interpreted).

However, I remembered that colors and paging work fine in `git` even when setting `PAGER=less`. It turns out that what they do is to pass the `-R` flag by setting the `LESS` environment variable, which has the virtue of affecting not only the `less` pager directly invoked by `cmdliner` but also when it is invoked through the `PAGER` variable.

https://github.com/git/git/commit/25fc1786ab147daa9ffa43ebcbaf5c1cc6e50d4f

I'm not sure how to set the environment variable without using `Unix`, though...

**Comment by dbuenzli** [comment]
I have to admit that with the age my patience with dealing with broken and undesigned systems is reaching zero.

If someone is willing to sift through all these ruins, idiosyncrasies and duct tape to provide me with a clear spec of what needs to be done so that everything works correctly I'm happy to implement it. But I have neither the energy nor the envy to research it. 

> I'm not sure how to set the environment variable without using `Unix`, though...

Well `system(3)` is supposed to interpret the given expression via a POSIX shell so I guess we could use `VAR=value cmd` but of course this would have to survive all the insane quotation layers and the likely various broken implementations of `system`.

**Comment by dbuenzli** [comment]
> I guess we could use VAR=value cmd

So 1de361182abcb809bbc98 does that, though I'm pretty sure I'm getting myself involved in more unpleasantness.

Taking from my (sanely implemented via unix) pager abstraction [here](https://github.com/b0-system/b0/blob/152c47864e9da478027bfa1113b892334abecffc/src/b00/kit/b00_pager.ml#L54-L58)
I use `FRX` rather than `FRSX`. The difference seems to be related to wrapping, horizontal scrolling is rather unconvenient but if people have a reason to add that `S` I could be convinced to add it.

**Comment by nojb** [comment]
> > I guess we could use VAR=value cmd
> 
> So [1de3611](https://github.com/dbuenzli/cmdliner/commit/1de361182abcb809bbc9856238b958b12039efd7) does that, though I'm pretty sure I'm getting myself involved in more unpleasantness.

Good guess :)

`system(3)` passes the string to `cmd.exe` on Windows which is not POSIX. In particular I don't think the syntax `VAR=xxx prog args` is understood by it. Some googling indicates that the right syntax for `cmd.exe` would be something like `set LESS=FRX && less <args>`. It seems to work for the `less` invocation in https://github.com/dbuenzli/cmdliner/issues/166#issuecomment-1382453391.

**Comment by dbuenzli** [comment]
Thanks! https://github.com/dbuenzli/cmdliner/commit/f239981642aefc2792382a1417c690bb6eaeb264 does what you suggest.

**Comment by nojb** [comment]
I think this can be closed. I haven't tested again after the latest fix (I'm waiting for #166 before testing again), but I believe it should have solved the problem.
