### ISSUE TITLE
support for `exec`-style commands without using `--`?

### ISSUE THREAD

**Issue by gasche** [dbuenzli/cmdliner#183]
Currently we have to write

```
opam exec --switch=4.14 -- ocamlc -version
dune exec -- minigen --exhaustive --depth 4
```

but the `--` is a bit annoying -- beginners are often tripped by this, they forget it and the error message can be fairly confusing.

```
$ opam exec --switch=4.14 ocamlc -config
opam: unknown option `-c'.
Usage: opam exec [OPTION]... COMMAND [ARG]......
Try `opam exec --help' or `opam --help' for more information.
```

Would it be possible to have support in cmdliner for

```
opam exec --switch=4.14 ocamlc -version
```

?

The semantics I would expect is the following:
- before the first non-optional argument, the optional arguments, here `--switch=4.14` are passed to `opam exec`
- the first non-optional argument, here `ocamlc`, collects all further arguments

Currently it is possible with `Arg.pos_right` to collect all positional arguments to the right of a given positional argument. Would a new combinator allow to collect all kind of arguments instead?

(It would be nice if this feature could be used to remove hardcoded support for `--` in the implementation.)

**Comment by dbuenzli** [comment]
No. `--` is a *feature*.

(There must be a previous discussion about exactly this from `dune` people but I can't find it. Nor here nor on `dune`'s tracker. Maybe it happened somewhere else)

Everything becomes all too ambiguous and context sensitive once you start doing these kind of things. For example for discriminating between the (possibly optional) argument of an option, a positional argument and a (possibly optional) command name (which in turn finally defines the grammar parsed for the command line).

This leads to even more puzzling error reporting and cli behaviours. Besides, in general, context *insensitive* cli are much more usable, they make it easier to interactively refine invocations from history[^1].

More generally:

1. `--` is not *annoying*, not the slightest bit: it brings clarity. Especially in the context of tools that run other tools (and recursively): it precisely delimits the scope for arguments for each of the levels of invocations. Personally I routinely have two such levels (but maybe that's because I also work on build systems).
2. `--` is something beginners may have to learn but it's both a [POSIX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html) and a [GNU](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) standard. It's not a `Cmdliner` idiosyncrasy.
3. Being a standard removing the hardcoded support for `--` is *out of the question*. If everyone makes a pet peeve choice whether to use it or not then the standard is moot and end users need to remember for each of their tool if it supports the standard or not when they make an invocation. We don't care about cli tool author pet peeves here, we care about uniform cli behaviour for end-users and good cli standards.

Aside, if you write you own `exec`-style commands you should always redefine the synopsis yourself in the help in order to show the `--` token (see for example [here] and [here][here3]). Also always use the token in documentation and tutorials, basically you should teach users and yourself to always use it. It should become a reflex as if it was mandatory[^2]. Always having it makes it easier to interactively refine invocations from history.

[here]: https://github.com/b0-system/b0/blob/cee572faf1a459e6f146a69a3518e4899415af93/src/tool/b0_cmd_build.ml#L363-L368
[here3]: https://github.com/b0-system/brzo/blob/73a63458145c09954b9eeccf03edd655e75fb2d3/src/brzo_main.ml#L43

[^1]: I'm already quite annoyed that due to the fact that I used an option with an optional argument for `--help` in `cmdliner`, using the `--help` flag is context sensitive.
[^2]: Of course it's not as long as you don't try to specify a flag to your sub-invocation.
