### ISSUE TITLE
how to add a default value that is computed at runtime in the manpage

### ISSUE THREAD

**Issue by zapashcanon** [dbuenzli/cmdliner#184]
Hi,

I have the following code:

```ocaml
let workers =
  let doc = "number of workers for symbolic execution" in
  Cmdliner.Arg.(
    value
    & opt int (Domain.recommended_domain_count ())
    & info [ "workers"; "w" ] ~doc )
```

This renders as:

```manpage
       -w VAL, --workers=VAL (absent=4)
           number of workers for symbolic execution
```

I am wondering if there is a way to render it as something like the following:

```manpage
       -w VAL, --workers=VAL (absent=`Domain.recommended_domain_count ()`)
           number of workers for symbolic execution
```

Thanks!

**Comment by dbuenzli** [comment]
There is, there is. [See](https://erratique.ch/software/cmdliner/doc/Cmdliner/Arg/index.html#val-info) the `absent` parameter of `info`:

```ocaml
 Cmdliner.Arg.(
    value
    & opt int (Domain.recommended_domain_count ())
    & info [ "workers"; "w" ] ~doc 
      ~absent:"Domain.recommended_domain_count ()"
```

That being said 

1. End users may actually prefer to see the actual value or 
   perhaps you could format absent with the value and say that it 
   depends on the machine.
2. Please ask these questions on https://discuss.ocaml.org
   (you are forgiven since it seems `cmdliner`'s README [does 
    not](https://github.com/dbuenzli/cmdliner?tab=readme-ov-file#documentation) show my [standard blurb](https://github.com/dbuenzli/cmarkit/tree/main?tab=readme-ov-file#documentation)).

**Comment by zapashcanon** [comment]
Thanks a lot for the solution (and for forgiving me!)
