### ISSUE TITLE
utf-8 being generated on non-Unicode locales

### ISSUE THREAD

**Issue by pmetzger** [dbuenzli/cmdliner#189]
See: https://github.com/ocaml/opam/issues/6076 — on a shell / terminal where `LANG` is set to `C`, generated help is producing Unicode characters that cannot be displayed successfully. Example:

<img width="573" alt="image" src="https://github.com/dbuenzli/cmdliner/assets/1907413/5eacd78e-dda0-4c12-9e45-c6acc9113664">

**Comment by dbuenzli** [comment]
I rather think your problem is with `LC_CTYPE`, I can't reproduce that with the first invocation, but I can with the second one:

```
LANG=C opam --help        # No problem
LC_CTYPE=C opam --help    # Problem
LANG=C LC_CTYPE=UTF-8 opam --help # No problem
```

At some point we decided to be in favour of allowing UTF-8 encoded manpages, because it was… 2021. There's a long discussion [here](https://github.com/dbuenzli/cmdliner/issues/27) about the arcane cross-platform way we found to achieve this in this utterly arcane system.

Regarding changing the encoding depending on which `LANG`, `LC_TYPE` or whatever `LOCALE` you have, I'm afraid we are not going to do that because it's 2024 and trying to transcode UTF-8 to whatever crazy encoding you are allowed to put in these variables is not going to happen, if only possible. It's time for US-ASCII to go.

For reference here's my output of `locale`. I have *no idea* how/where these variables get set, only that as far as I see I have nothing in my `.zprofile` or `.zshrc` that does so.

```
> locale
locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by pmetzger** [comment]
On my Mac: `env | fgrep LC` is empty. `locale` prints something quite different, but those variables aren't in my environment (and are not exported).

Unfortunately, some of us aren't in a good position to make US ASCII go. For example, if I turn on Unicode in my terminal, I can no longer use the meta key in Emacs over SSH sessions (and I remote manage a lot of stuff.) This might be a small issue to other people, but there are a lot of people with small issues like this. People in the far east often prefer non-Unicode character sets because they don't like the way Han unification was done. There are people who want to look at old OCaml code that is still in Latin-1 for whatever reason.

**Comment by dbuenzli** [comment]
Well I wouldn't like to [disappoint](https://github.com/ocaml/opam/issues/6076#issuecomment-2217839106)  @pmetzger. 

Fix your systems.
