### ISSUE TITLE
Having LANG=C in your environment outputs incorrect characters

### ISSUE THREAD

**Issue by kit-ty-kate** [dbuenzli/cmdliner#190]
https://github.com/dbuenzli/cmdliner/issues/189#issuecomment-2217847906

**Comment by kit-ty-kate** [comment]
> or whatever program cmdliner's output is being fed to

which pager are you using? I've tried all the ones i know but only `more` works (displays utf-8 character correctly)

**Comment by dbuenzli** [comment]
Look if you put `LANG=C` without further characterizing `LC_CTYPE` you get a non UTF-8 environment. See my response in the other thread. What do you expect cmdliner to do in this setting ? 

Some people pushed for UTF-8 manpages a wish that was granted in 2021 because it's a reasonable request at that point in time. So cmdliner users expect to be able to write UTF-8 encoded data in manpages nowadays.

And please stop wasting my time "with this works that doesn't work". Understand how the broken posix locale system works (I half do). If you think there's something sensitive that can be about it in cmdliner then tell me. But I'm not wasting any more second on this, I'm rather pissed off at that point. I took the time to come up with a reasonable answer in the other issue (basically set `LC_CTYPE` to `UTF-8`) only to be insulted by behind.
