### ISSUE TITLE
Default command with positional arg

### ISSUE THREAD

**Issue by mbarbin** [dbuenzli/cmdliner#195]
While writing some tests in the cmdlang project, I noticed a case that I thought may be interesting to report.

Not all command libs I've looked at support a default command within a group, but cmdliner does. However, if this default command expects a positional argument, it would seem the execution engine is defeated (it fails, trying to interpret the argument as the name of a subcommand).

I have a case that looks like this here:

https://github.com/mbarbin/cmdlang/blob/09586616c9256e8335bc56b7593fa00cd425616c/test/cram/group.t#L289

**Comment by dbuenzli** [comment]
If your default command has positional arguments then it becomes ambiguous. You need to specify them after the [standard `--` token](https://erratique.ch/software/cmdliner/doc/cli.html#posargs). 

Well a positional argument becomes ambiguous in a command group with a default command becomes ambiguous. You need to specify them after a `--` if they

**Comment by mbarbin** [comment]
I don't have a compelling use case. I will simply note that e.g. climate and cmdlang's stdlib-runner take the alternate strategy to favor the first positional argument as a candidate for the group hierarchy and check for that first. This makes things work in common cases, although, yes you cannot call your default command with a first positional argument that is named as the name of an existing subcommand. It's possibly just a different tradeoff, I'm not sure yet whether I have a strict preference for either strategy.

Thanks for looking!

**Comment by dbuenzli** [comment]
> It's possibly just a different tradeoff, I'm not sure yet whether I have a strict preference for either strategy.

It's not a tradeoff, it's a bad idea. 

First it will confuse your users the day they call your command with a positional argument that is named after one of the subcommands. Second it's not stable with additions: users may devise command lines that may fail in the future due to the additions of new subcommands. Don't do that. 

In general it's better to avoid default subcommands. If users really want it, it's better if they don't have positional arguments. If they really want it then educate them to always use `--` to disambuigate. See also [this discussion]. 

[this discussion]: https://github.com/dbuenzli/cmdliner/issues/183

**Comment by mbarbin** [comment]
> First it will confuse your users the day they call your command with a positional argument that is named after one of the subcommands. Second it's not stable with additions: users may devise command lines that may fail in the future due to the additions of new subcommands. Don't do that.

I'm buying your Second point here, thanks!

But I'm starting to think that I'm getting somewhat confused. The help for the '--' standard in [GNU](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) says:

> The argument -- terminates all options; any following arguments are treated as non-option arguments, even if they begin with a hyphen.

By that definition, if you use the separator you are not able to use options for the default command. For example the `--flag` below would be interpreted as a positional argument.

```sh
$ ./main.exe group -- hello --flag
```

I am understanding then that default commands should either have *only* options, in which case they must be invoked *without* the separator, or have *only* positional arguments, in which case they must be invoked *with* the separator, but no combinations would work. Is that right? (that sounds surprising).

I guess I always thought of '--' it as a special separator that you would need, as a cli author, to explicitly specify for it to be accepted in a command - usually for passing the remaining arguments (and options) to another program. I guess I am discovering now that e.g. `dune exec my-program my-pos-arg` works and invokes `my-program my-pos-arg` (I had no idea, and thought `dune exec my-program -- my-pos-arg` was mandatory. Enlightening!

> In general it's better to avoid default sub-commands.

Personally I agree. That might be due to a bias towards strongly typed things :smiley:.  *So, is that a group, or a command? Wait..., it's _both_?!*

Thank you for the additional context, which I find helpful.

**Comment by dbuenzli** [comment]
> Is that right?

No.

**Comment by mbarbin** [comment]
> > Is that right?
> 
> No.

OK, I'll add some more tests to investigate, because I am definitely confused. I am imagining that perhaps the following works:

```sh
$ ./main.exe group --flag -- hello
```

which shows a syntax for successfully invoking a default group command that combines positional and flags. Is the separator necessary when the invocation starts with a flag? (as there is no ambiguity then).

If you have other examples in mind, I'll add those as well in my test suite. Thank you!

**Comment by dbuenzli** [comment]
I think it would be worth for you to read or reread the [basic documentation](https://erratique.ch/software/cmdliner/doc/cli.html#cmdline) about cmdliner.

In general if you have a command line and an argument fails to be treated by the parsing machinery as positional you can simply add `--` and everything afterwards becomes a positional argument no question asked. That's all (and both a POSIX and GNU convention, which you should also perhaps (re)read).

There are likely more cases than you currently think where this can happen. For example when you have an optional argument that has a default value and you want to specify a positional argument just afterwards.

Now in the particular case of subcommands[^1], if a command has subcommands and a default subcommand, then a positional argument is made unconditionally ambiguous[^2]. So it always has to be specified after a `--` token, that's all. That in turn is just the basic rule I highlighted in the second paragraph.

[^1]: I think it's better not to talk about groups, that terminology is for the API not for cli users.
[^2]: Because trying to be smart about it always ends up being more confusing for end users or having them to learn more (e.g. introduce an escape syntax)
