### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fxfactorial** [dbuenzli/cmdliner#41]
Would be nice if for file Cmdliner could give me back absolute paths if I wanted that.

**Comment by dbuenzli** [comment]
What are you talking about ?

**Comment by fxfactorial** [comment]
There is the existing type: `Cmdliner.Arg.file`. In my evaluating function that actually get the value for a variable of type `file`, then I get a string. I'm saying it would be nice if I could get an absolute path.

**Comment by dbuenzli** [comment]
It's a little bit unclear if you want the converter to check whether the given file is absolute or not  and error otherwise or if you simply want the file to be transformed to an absolute path according to `Sys.get_cwd ()`. 

In any case there are a little bit too many things that one may want to have here (e.g. `realpath(3)`, no dot segments, handling of windows absolute path etc.) so I think you should rather define your own converter that does exactly what you want.
