### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by tekknolagi** [dbuenzli/cmdliner#66]
Would it be possible to add a type of argument that can represent deprecated flags? Ideally they would not show up in the `--help` page, but when used would warn/error.

If you don't have time to implement, point me in the right direction and I can submit a PR.

**Comment by dbuenzli** [comment]
@snowleopard wants to be able to deprecate commands.  

None of this seems unreasonable and unfeasible. The idea is to add a `?deprecated:string` argument to info structures. That string should be output on the error formatter if the corresponding argument/command is used.

Both @tekknolagi and @snowleopard do not want these arguments/commands to be listed in the help pages. This seems a bit user hostile to me, if you are facing deprecated invocations it's still useful to know what they do. 

I think we should simply mark them as deprecated in some way in the docs.

**Comment by samoht** [comment]
Maybe adding these arguments to a new section at the end of the man page is a good compromise?

**Comment by tekknolagi** [comment]
I haven't used OCaml in years at this point so I don't have so many
opinions any more :)

**Comment by dbuenzli** [comment]
> I haven't used OCaml in years at this point so I don't have so many opinions any more :)

Come back… :–)

Good idea @samoht. That is if `deprecated` is specified the `?docs` argument that specifies the section in which the element is documented defaults to a new `Manpage.s_deprecated` section rather than `Manpage.s_options` or `Manpage.s_commands`.

**Comment by tekknolagi** [comment]
I think having a `DEPRECATED` section of the man page and maybe a `(deprecated)` in the `--help` would be fine, in retrospect. I think I had one or two annoying use-cases at work where I wanted them not to be listed, but  ¯\_(ツ)_/¯ 

> Come back… :–)

Alas, I am currently writing runtimes in C++

**Comment by dbuenzli** [comment]
> I think I had one or two annoying use-cases at work where I wanted them not to be listed, but ¯_(ツ)_/¯

In fact we could have a `Manpage.s_dev_null` section for these cases to prevent listing. Just not the default.

> Alas, I am currently writing runtimes in C++

I'm sure it can be fun too.

**Comment by snowleopard** [comment]
> In fact we could have a `Manpage.s_dev_null` section for these cases to prevent listing. Just not the default.

That sounds perfect to me.

**Comment by dbuenzli** [comment]
/cc @rgrinberg who may also be interested in that

I added support for deprecating *commands* (will look into arguments tomorrow).

1. I added a `deprecated` argument to `Cmd.info`, when specified this 
is the message to output when the command is used.
2. For the manual,  rather than put them in a dedicated section. I just prefix their synopsis with `(Deprecated)`. This means they get listed at the end in the natural section where you'd find them (see below). I think it's better than a single "DEPRECATED" section or "DEPRECATED COMMANDS", "DEPRECATED OPTIONS", etc. sections.
2. I added `Manpage.s_none` a special section that is never rendered, if you really want to hide things that exist to users (better not though).

Here's an example when you try to use a [deprecated command](https://github.com/dbuenzli/cmdliner/blob/ed6d829156d1a86f56973f87e8b151802029c11e/test/test_nest.ml#L41-L46):

```
> test_nest camels        
test_nest: The 'camels' function is deprecated use 'mammals' instead.
```
Here's an example on how it renders in the parent of a deprecated command  : 
```
NAME
       test_nest

SYNOPSIS
       test_nest COMMAND ...

COMMANDS
       birds [COMMAND] ...
           Operate on birds.

       fishs [OPTION]... [NAME]
           Operate on fishs.

       mammals [OPTION]...
           Operate on mammals.

       (Deprecated) camels [OPTION]...
           Operate on camels.

OPTIONS
       --help[=FMT] (default=auto)
           Show this help in format FMT. The value FMT must be one of auto,
```
And in the help of the command itself you get: 
```
NAME
       test_nest-camels - Operate on camels.

SYNOPSIS
       (Deprecated) test_nest camels [OPTION]...

OPTIONS
       --help[=FMT] (default=auto)
           Show this help in format FMT. The value FMT must be one of auto,
  
```

**Comment by dbuenzli** [comment]
Arguments and environment variables (if actually looked up) can now be deprecated in a similar way, separately. 

I slightly tweaked the output format to always mention the entity that talks about its deprecation so that you don't have to mention it in the message itself. For example with [these](https://github.com/dbuenzli/cmdliner/blob/a9074b68328c18b007a0c84b410412cf46f87603/test/test_nest.ml#L41-L56) deprecations:  

```
> BACTRIAN=true test_nest camels bla
test_nest: command 'camels': deprecated, use 'mammals' instead.
           argument 'bla': deprecated, herds are ignored.
test_nest: environment variable BACTRIAN: deprecated, use nothing instead.
```
In the manpages deprecated stuff is consistently prefixed with `(Deprecated)` and we make sure in lists to put them at the end (if you don't want them to be listed use the new `Manpage.s_none`).

```
NAME
       (Deprecated) test_nest-camels - Operate on camels.

SYNOPSIS
       (Deprecated) test_nest camels [OPTION]... [HERD]

ARGUMENTS
       (Deprecated) HERD
           Find in herd HERD.

OPTIONS
       --help[=FMT] (default=auto)
           Show this help in format FMT. The value FMT must be one of auto,
           pager, groff or plain. With auto, the format is pager or plain
           whenever the TERM env var is dumb or undefined.

       --version
           Show version information.

       (Deprecated) -b, --bactrian (absent BACTRIAN env)
           Specify a bactrian camel.

EXIT STATUS
       camels exits with the following status:

       0   on success.

       123 on indiscriminate errors reported on standard error.

       124 on command line parsing errors.

       125 on unexpected internal errors (bugs).

ENVIRONMENT
       These environment variables affect the execution of camels:

       (Deprecated) BACTRIAN
           See option --bactrian.

SEE ALSO
       test_nest(1)
```
