### ISSUE TITLE
Interest in NodeJS backend?

### ISSUE THREAD

**Issue by bobzhang** [dbuenzli/cmdliner#84]
Yesterday, I tested it on BuckleScript, it works out of box except that `man` page which relies on File IO operation. 
I think this is useful library and would like to bringing it to NPM. Before I proceed, I would like to know what's your stance on porting to NPM, and for platform dependent behavior(IO stuff), what's the recommended way for patches (cppo, or a specialized ppx?)
Thanks

**Comment by dbuenzli** [comment]
Why don't you port the file IO operations ?

**Comment by bobzhang** [comment]
Since OCaml  channel is lower level than what Node provides, it is imprecise and ugly to polyfill low level stuff using high level primitives.

**Comment by dbuenzli** [comment]
So what do you suggest exactly ? It seems to me that the way `js_of_ocaml` solved this works quite well in practice.

**Comment by bobzhang** [comment]
They have different purposes. BuckleScript want to deliver optimal js while jsoo want to run as much as ocaml(including some runtime hacks).
Thanks for your suggestions

**Comment by dbuenzli** [comment]
> They have different purposes. BuckleScript want to deliver optimal js while jsoo want to run as much as ocaml(including some runtime hacks).

I'm not exactly sure what you are answering here. My question was how you saw solving this this problem so that NodeJS programs using cmdliner would be observationally equivalent to ocaml ones cli-wise (e.g. manpage paging etc.). 

My take on this is that a `Sys` and  OCaml channel abstraction compatibility library for bucklescript users to link against should be provided since this will solve the problem for many other OCaml libraries. I'm not sure every package out there having to special case for bucklescript is a viable strategy. Besides I fail to see how this relate to the different purposes you mention.

**Comment by bobzhang** [comment]
> OCaml channel abstraction compatibility library

This is quite difficult, jsoo simulate it to some extent, but it is not really exact. 
An easy route is to design a high level IO interface that is easy to be polyfilled on different backends.

Maybe in the future, we can do some work to polyfill the channel(I have a very long to-do list), but it could be useful that we can port some existing ocaml libraries to npm to sell to other JS developers, without doubt, cmdliner is probably the best command line parsing library on npm if we  can port it there.
