### ISSUE TITLE
Version string from git or opam?

### ISSUE THREAD

**Issue by orbifx** [dbuenzli/cmdliner#90]
Is there a way to automatically inject the version string from the `.opam` file or Git's describe?

**Comment by dbuenzli** [comment]
Since your `opam` file should be in your repo you should never have a version number there. If you use `topkg` simply set the version to `%%VERSION%%` the [watermaking process](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALdistdetails) will take care of it. This will give you precise version numbers on opam pins/releases.

**Comment by dbuenzli** [comment]
Btw. these questions are best discussed on https://discuss.ocaml.org/

**Comment by dbuenzli** [comment]
The link was wrong see here http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#distdetails
