### ISSUE TITLE
Failing to display help (format pager) after js_of_ocaml

### ISSUE THREAD

**Issue by budde377** [dbuenzli/cmdliner#92]
When compiling my program to JavaScript, Cmdliner fails to display `--help=pager` with the following error:

```
type less 1>/dev/null 2>/dev/null
type groff 1>/dev/null 2>/dev/null
groff -Tascii -P-c < /var/folders/vj/5ryqcgbd46g3zmrb7z62lh8c0000gn/T/sdkitty.js1593bbout | less
troff: warning: can't find character with input code 12
```

This can be reproduced by compiling the example program at http://erratique.ch/software/cmdliner/doc/Cmdliner#exrm to JavaScript with `js_of_ocaml`.

**Comment by dbuenzli** [comment]
Could you check the output of `--pager=groff` and try to `groff` it to see if the same error occurs. Besides how/where do you run the JavaScript ? Please provide the full steps to reproduce.

**Comment by budde377** [comment]
I'm not totally sure what you mean with `--pager=groff`, but `--help=groff` does not return the error, and `--help=groff | groff` correctly returns the documentation.
I'm running the program on `macOS 10.13.3` with node version `v8.1.4`.

**Comment by dbuenzli** [comment]
> I'm not totally sure what you mean with --pager=groff

Sorry yes `--help=groff`. Could you please provide precise the list of compilation steps and invocations to reproduce.

**Comment by dbuenzli** [comment]
Also does the issue occur if you compile to OCaml byte or native code ?

**Comment by budde377** [comment]
Here is a minimal example which should be enough to reproduce the problem.

https://gist.github.com/budde377/b6ffa0180aa4c49bbec3ef10f3ec8f65

So creating these three files and running

```
jbuilder build main.bc.js
```

creates a JS file, which run with `node ./build/default/main.bc.js --help=pager` brings the error above.  I do not observe the error in OCaml byte or native code.

**Comment by dbuenzli** [comment]
Thanks for the repro case. Note that here (node v8.8.1, macOS 10.12.6, groff 1.19.2) this warning is nowhere to be seen:
```
troff: warning: can't find character with input code 12
```
The program simply prints the commands that are `Sys.command`ed on stdout and stops. The problem seems rather to be the implementation of `Sys.command` in `js_of_ocaml` which you can find [here](https://github.com/ocsigen/js_of_ocaml/blob/e0824e0b5aa5a172bdbbb05d5029c5fa55200be6/runtime/stdlib.js#L949). In particular commands should not be printed on stdout and no IO redirection occurs from the child process to the parent one. You can convince yourself by replacing `main.ml` with:

```
let () = ignore (Sys.command "less main.ml")
```
and then running: 
```
_build/default/main.bc
```
which will page you into `less` versus the following which doesn't page you but simply prints out the command invoked on stdout (which it should not).
```
$ node _build/default/main.bc.js
less main.ml
```
So except for that dubious `troff` warning I don't think there's a problem with cmdliner here. Could you however please give me the output of `groff --version` on your machine and indicate me if the warning also occurs when you groff manually the output.

**Comment by dbuenzli** [comment]
Oh and the printing we are seing is certainly due to this [line](https://github.com/ocsigen/js_of_ocaml/blob/e0824e0b5aa5a172bdbbb05d5029c5fa55200be6/runtime/stdlib.js#L951). You should open something upstream.

**Comment by budde377** [comment]
Thank you for investigating!
Here's the output of `groff --version` is:
```
GNU groff version 1.19.2
Copyright (C) 2004 Free Software Foundation, Inc.
GNU groff comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of groff and its subprograms
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

called subprograms:

GNU grops (groff) version 1.19.2
GNU troff (groff) version 1.19.2
```
I see now that the warning isn't being reproduced in the example I sent, rather:
```
type less 1>/dev/null 2>/dev/null
type groff 1>/dev/null 2>/dev/null
groff -Tascii -P-c < /var/folders/vj/5ryqcgbd46g3zmrb7z62lh8c0000gn/T/main.bc.jsae590dout | less
```
which sounds like what you see.
