### ISSUE TITLE
Allow options before the sub-command

### ISSUE THREAD

**Issue by diml** [dbuenzli/cmdliner#94]
In Dune, we have a lot of options that are common to all sub-commands. However it doesn't seem possible to tell that to the cmdliner. As a result, the user cannot do something like that:

```bash
$ alias jbuilder="jbuilder --display verbose"
```

which is a bit annoying.

**Comment by dbuenzli** [comment]
I don't think this is possible the issue here is ambiguities between positional arguments, command names and detached optional argument values. If you find a way a PR is welcome but IIRC there's a good reason why this is the case. 

Note that for that particular example is seems you rather want to use environment variables to override a default rather than an alias.
